from .asistencias import AsistenciaSerializer
from .asistentes import AsistenteSerializer
from .carreras import CarreraSerializer
from .conferencias import ConferenciaSerializer
from .conferencistas import ConferencistaSerializer
from .cuentas import CuentaSerializer
from .estudiantes_umg import EstudianteUmgSerializer
from .pagos import PagoSerializer
from .reservaciones import ReservacionSerializer
from .salones import SalonSerializer
from .tickets import TicketSerializer
