# Generated by Django 3.0.3 on 2020-02-23 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('first_login', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asistente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conferencista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('profesion', models.CharField(max_length=150)),
                ('resumen', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=30, verbose_name='Número de cuenta')),
                ('banco', models.CharField(max_length=30, verbose_name='Banco')),
                ('titular', models.CharField(max_length=30, verbose_name='Titular')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pago', models.CharField(max_length=30, verbose_name='Número de cuenta')),
                ('foto', models.FileField(upload_to='', verbose_name='Foto')),
                ('titular', models.CharField(max_length=30, verbose_name='Titular')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('estado', models.SmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Pagado')], default=0, verbose_name='Estado')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='administracion.Cuenta', verbose_name='Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('capacidad', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ValidacionPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=300, verbose_name='Mensaje')),
                ('resultado', models.SmallIntegerField(choices=[(1, 'Por verificar'), (2, 'Verificado')], default=1, verbose_name='Resultado')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Validaciones', to='administracion.Pago', verbose_name='Pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Validaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.CharField(max_length=200)),
                ('estado', models.SmallIntegerField(choices=[(1, 'VENDIDO'), (2, 'NO VENDIDO')], default=2, verbose_name='ESTADOS')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ticket', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteUmg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet', models.CharField(max_length=25)),
                ('semestre', models.SmallIntegerField()),
                ('codigo_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EstudianteUmg', to='administracion.Carrera', verbose_name='Carrera')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EstudianteUmg', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('conferencista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Conferencista')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Salon')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asistencia', to='administracion.Conferencia', verbose_name='Conferencia')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asistencia', to='administracion.Ticket', verbose_name='Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('estado', models.SmallIntegerField(choices=[(1, 'PAGADA'), (2, 'NO PAGADA')], default=2, verbose_name='ESTOS')),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reservacion', to='administracion.Asistente', verbose_name='Usuario')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reservacion', to='administracion.Conferencia', verbose_name='Conferencia')),
            ],
            options={
                'index_together': {('asistente', 'conferencia')},
            },
        ),
    ]
