# Generated by Django 2.2.5 on 2020-03-25 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferencias', to='administracion.Salon'),
        ),
        migrations.AlterField(
            model_name='evaluacionreembolso',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_reembolso', to='administracion.Pago', verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='conferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='administracion.Conferencia', verbose_name='Conferencia'),
        ),
        migrations.AlterField(
            model_name='validacionpago',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='administracion.Pago', verbose_name='Pago'),
        ),
    ]
