# Generated by Django 2.2.5 on 2020-02-27 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='codigo_pago',
            field=models.CharField(max_length=30, unique=True, verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.SmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Rechazado'), (3, 'Aceptado'), (4, 'Reembolso solicitado'), (5, 'Reembolso aprobado'), (6, 'Reembolsado')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='titular',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asistente', to='administracion.Asistente', verbose_name='Asistente'),
        ),
    ]
