# Generated by Django 2.2.5 on 2020-02-27 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20200226_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacionpago',
            name='time_validacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='validacionpago',
            name='resultado',
            field=models.SmallIntegerField(choices=[(2, 'Rechazado'), (3, 'Aceptado'), (5, 'Reembolso aprobado'), (6, 'Reembolsado')], verbose_name='Resultado'),
        ),
    ]
