# Generated by Django 2.2.5 on 2020-03-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20200310_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='foto',
            field=models.ImageField(default='none', upload_to='conferencias'),
        ),
    ]
