# Generated by Django 2.2.5 on 2020-02-28 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20200226_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Asistente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
