# Generated by Django 2.2.5 on 2020-03-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_conferencia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='estado',
            field=models.SmallIntegerField(choices=[(1, 'Confirmada'), (3, 'Pago pendiente de validar'), (4, 'Pago sin registrar')], default=1, verbose_name='Estado'),
        ),
    ]
