# Generated by Django 2.2.5 on 2020-02-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20200227_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
