# Generated by Django 2.2.5 on 2020-02-28 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20200227_2034'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together={('numero_cuenta', 'banco')},
        ),
    ]
