# Generated by Django 2.2.5 on 2020-03-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20200227_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='codigo',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
