# Generated by Django 2.2.5 on 2020-03-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_auto_20200302_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='foto',
            field=models.TextField(verbose_name='Foto'),
        ),
    ]
