# Generated by Django 2.2.5 on 2020-03-03 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_auto_20200302_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudianteumg',
            name='codigo_carrera',
        ),
        migrations.RemoveField(
            model_name='estudianteumg',
            name='usuario',
        ),
        migrations.AddField(
            model_name='estudianteumg',
            name='asistente',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='EstudianteUmg', to='administracion.Asistente', verbose_name='Asistente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudianteumg',
            name='carrera',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='administracion.Carrera', verbose_name='Carrera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudianteumg',
            name='carnet',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='estudianteumg',
            name='semestre',
            field=models.PositiveSmallIntegerField(verbose_name='Semestre'),
        ),
    ]
