# Generated by Django 2.2.5 on 2020-03-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_auto_20200302_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='titular',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='administracion.Asistente', verbose_name='Asistente'),
        ),
    ]
