# Generated by Django 2.2.5 on 2020-03-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_auto_20200303_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='hora',
            field=models.TimeField(null=True, verbose_name='Hora'),
        ),
    ]
